export const countryCodes = [
  { name: "India", code: "+91", regex: /^[6-9]\d{9}$/ },
  { name: "Afghanistan", code: "+93", regex: /^\d{9}$/ },
  { name: "Albania", code: "+355", regex: /^\d{9}$/ },
  { name: "Algeria", code: "+213", regex: /^\d{9}$/ },
  { name: "Andorra", code: "+376", regex: /^\d{6}$/ },
  { name: "Angola", code: "+244", regex: /^\d{9}$/ },
  { name: "Antigua and Barbuda", code: "+1-268", regex: /^\d{7}$/ },
  { name: "Argentina", code: "+54", regex: /^\d{10}$/ },
  { name: "Armenia", code: "+374", regex: /^\d{8}$/ },
  { name: "Australia", code: "+61", regex: /^\d{9}$/ },
  { name: "Austria", code: "+43", regex: /^\d{10}$/ },
  { name: "Azerbaijan", code: "+994", regex: /^\d{9}$/ },
  { name: "Bahamas", code: "+1-242", regex: /^\d{7}$/ },
  { name: "Bahrain", code: "+973", regex: /^\d{8}$/ },
  { name: "Bangladesh", code: "+880", regex: /^\d{10}$/ },
  { name: "Barbados", code: "+1-246", regex: /^\d{7}$/ },
  { name: "Belarus", code: "+375", regex: /^\d{9}$/ },
  { name: "Belgium", code: "+32", regex: /^\d{9}$/ },
  { name: "Belize", code: "+501", regex: /^\d{7}$/ },
  { name: "Benin", code: "+229", regex: /^\d{9}$/ },
  { name: "Bhutan", code: "+975", regex: /^\d{8}$/ },
  { name: "Bolivia", code: "+591", regex: /^\d{8}$/ },
  { name: "Bosnia and Herzegovina", code: "+387", regex: /^\d{8}$/ },
  { name: "Botswana", code: "+267", regex: /^\d{7}$/ },
  { name: "Brazil", code: "+55", regex: /^\d{10,11}$/ },
  { name: "Brunei", code: "+673", regex: /^\d{7}$/ },
  { name: "Bulgaria", code: "+359", regex: /^\d{9}$/ },
  { name: "Burkina Faso", code: "+226", regex: /^\d{8}$/ },
  { name: "Burundi", code: "+257", regex: /^\d{8}$/ },
  { name: "Cabo Verde", code: "+238", regex: /^\d{7}$/ },
  { name: "Cambodia", code: "+855", regex: /^\d{9}$/ },
  { name: "Cameroon", code: "+237", regex: /^\d{9}$/ },
  { name: "Canada", code: "+1", regex: /^\d{10}$/ },
  { name: "Central African Republic", code: "+236", regex: /^\d{8}$/ },
  { name: "Chad", code: "+235", regex: /^\d{8}$/ },
  { name: "Chile", code: "+56", regex: /^\d{9}$/ },
  { name: "China", code: "+86", regex: /^\d{11}$/ },
  { name: "Colombia", code: "+57", regex: /^\d{10}$/ },
  { name: "Comoros", code: "+269", regex: /^\d{7}$/ },
  { name: "Congo", code: "+242", regex: /^\d{9}$/ },
  { name: "Costa Rica", code: "+506", regex: /^\d{8}$/ },
  { name: "Croatia", code: "+385", regex: /^\d{9}$/ },
  { name: "Cuba", code: "+53", regex: /^\d{8}$/ },
  { name: "Cyprus", code: "+357", regex: /^\d{8}$/ },
  { name: "Czech Republic", code: "+420", regex: /^\d{9}$/ },
  { name: "Denmark", code: "+45", regex: /^\d{8}$/ },
  { name: "Djibouti", code: "+253", regex: /^\d{6}$/ },
  { name: "Dominica", code: "+1-767", regex: /^\d{7}$/ },
  { name: "Dominican Republic", code: "+1-809", regex: /^\d{10}$/ },
  { name: "Ecuador", code: "+593", regex: /^\d{9}$/ },
  { name: "Egypt", code: "+20", regex: /^\d{10}$/ },
  { name: "El Salvador", code: "+503", regex: /^\d{8}$/ },
  { name: "Equatorial Guinea", code: "+240", regex: /^\d{9}$/ },
  { name: "Eritrea", code: "+291", regex: /^\d{7}$/ },
  { name: "Estonia", code: "+372", regex: /^\d{8}$/ },
  { name: "Eswatini", code: "+268", regex: /^\d{8}$/ },
  { name: "Ethiopia", code: "+251", regex: /^\d{9}$/ },
  { name: "Fiji", code: "+679", regex: /^\d{7}$/ },
  { name: "Finland", code: "+358", regex: /^\d{9}$/ },
  { name: "France", code: "+33", regex: /^\d{9}$/ },
  { name: "Gabon", code: "+241", regex: /^\d{9}$/ },
  { name: "Gambia", code: "+220", regex: /^\d{7}$/ },
  { name: "Georgia", code: "+995", regex: /^\d{9}$/ },
  { name: "Germany", code: "+49", regex: /^\d{10,11}$/ },
  { name: "Ghana", code: "+233", regex: /^\d{9}$/ },
  { name: "Greece", code: "+30", regex: /^\d{10}$/ },
  { name: "Grenada", code: "+1-473", regex: /^\d{7}$/ },
  { name: "Guatemala", code: "+502", regex: /^\d{8}$/ },
  { name: "Guinea", code: "+224", regex: /^\d{9}$/ },
  { name: "Guyana", code: "+592", regex: /^\d{7}$/ },
  { name: "Haiti", code: "+509", regex: /^\d{8}$/ },
  { name: "Honduras", code: "+504", regex: /^\d{8}$/ },
  { name: "Hungary", code: "+36", regex: /^\d{9}$/ },
  { name: "Iceland", code: "+354", regex: /^\d{7}$/ },
  { name: "Indonesia", code: "+62", regex: /^\d{10,11}$/ },
  { name: "Iran", code: "+98", regex: /^\d{10}$/ },
  { name: "Iraq", code: "+964", regex: /^\d{10}$/ },
  { name: "Ireland", code: "+353", regex: /^\d{9}$/ },
  { name: "Israel", code: "+972", regex: /^\d{9}$/ },
  { name: "Italy", code: "+39", regex: /^\d{10}$/ },
  { name: "Jamaica", code: "+1-876", regex: /^\d{7}$/ },
  { name: "Japan", code: "+81", regex: /^\d{10}$/ },
  { name: "Jordan", code: "+962", regex: /^\d{9}$/ },
  { name: "Kazakhstan", code: "+7", regex: /^\d{10}$/ },
  { name: "Kenya", code: "+254", regex: /^\d{10}$/ },
  { name: "Kiribati", code: "+686", regex: /^\d{5}$/ },
  { name: "Kuwait", code: "+965", regex: /^\d{8}$/ },
  { name: "Kyrgyzstan", code: "+996", regex: /^\d{9}$/ },
  { name: "Laos", code: "+856", regex: /^\d{9}$/ },
  { name: "Latvia", code: "+371", regex: /^\d{8}$/ },
  { name: "Lebanon", code: "+961", regex: /^\d{7}$/ },
  { name: "Lesotho", code: "+266", regex: /^\d{8}$/ },
  { name: "Liberia", code: "+231", regex: /^\d{9}$/ },
  { name: "Libya", code: "+218", regex: /^\d{10}$/ },
  { name: "Liechtenstein", code: "+423", regex: /^\d{7}$/ },
  { name: "Lithuania", code: "+370", regex: /^\d{8}$/ },
  { name: "Luxembourg", code: "+352", regex: /^\d{9}$/ },
  { name: "Madagascar", code: "+261", regex: /^\d{9}$/ },
  { name: "Malawi", code: "+265", regex: /^\d{9}$/ },
  { name: "Malaysia", code: "+60", regex: /^\d{10}$/ },
  { name: "Maldives", code: "+960", regex: /^\d{7}$/ },
  { name: "Mali", code: "+223", regex: /^\d{8}$/ },
  { name: "Malta", code: "+356", regex: /^\d{8}$/ },
  { name: "Marshall Islands", code: "+692", regex: /^\d{7}$/ },
  { name: "Mauritania", code: "+222", regex: /^\d{8}$/ },
  { name: "Mauritius", code: "+230", regex: /^\d{8}$/ },
  { name: "Mexico", code: "+52", regex: /^\d{10}$/ },
  { name: "Micronesia", code: "+691", regex: /^\d{7}$/ },
  { name: "Moldova", code: "+373", regex: /^\d{8}$/ },
  { name: "Monaco", code: "+377", regex: /^\d{9}$/ },
  { name: "Mongolia", code: "+976", regex: /^\d{8}$/ },
  { name: "Montenegro", code: "+382", regex: /^\d{8}$/ },
  { name: "Morocco", code: "+212", regex: /^\d{9}$/ },
  { name: "Mozambique", code: "+258", regex: /^\d{9}$/ },
  { name: "Myanmar", code: "+95", regex: /^\d{9}$/ },
  { name: "Namibia", code: "+264", regex: /^\d{9}$/ },
  { name: "Nauru", code: "+674", regex: /^\d{7}$/ },
  { name: "Nepal", code: "+977", regex: /^\d{10}$/ },
  { name: "Netherlands", code: "+31", regex: /^\d{9}$/ },
  { name: "New Zealand", code: "+64", regex: /^\d{9}$/ },
  { name: "Nicaragua", code: "+505", regex: /^\d{8}$/ },
  { name: "Niger", code: "+227", regex: /^\d{8}$/ },
  { name: "Nigeria", code: "+234", regex: /^\d{10}$/ },
  { name: "Norway", code: "+47", regex: /^\d{8}$/ },
  { name: "Oman", code: "+968", regex: /^\d{8}$/ },
  { name: "Pakistan", code: "+92", regex: /^\d{10}$/ },
  { name: "Palau", code: "+680", regex: /^\d{7}$/ },
  { name: "Panama", code: "+507", regex: /^\d{8}$/ },
  { name: "Papua New Guinea", code: "+675", regex: /^\d{7}$/ },
  { name: "Paraguay", code: "+595", regex: /^\d{9}$/ },
  { name: "Peru", code: "+51", regex: /^\d{9}$/ },
  { name: "Philippines", code: "+63", regex: /^\d{10}$/ },
  { name: "Poland", code: "+48", regex: /^\d{9}$/ },
  { name: "Portugal", code: "+351", regex: /^\d{9}$/ },
  { name: "Qatar", code: "+974", regex: /^\d{8}$/ },
  { name: "Romania", code: "+40", regex: /^\d{9}$/ },
  { name: "Russia", code: "+7", regex: /^\d{10}$/ },
  { name: "Rwanda", code: "+250", regex: /^\d{9}$/ },
  { name: "Saint Kitts and Nevis", code: "+1-869", regex: /^\d{7}$/ },
  { name: "Saint Lucia", code: "+1-758", regex: /^\d{7}$/ },
  {
    name: "Saint Vincent and the Grenadines",
    code: "+1-784",
    regex: /^\d{7}$/,
  },
  { name: "Samoa", code: "+685", regex: /^\d{5,6}$/ },
  { name: "San Marino", code: "+378", regex: /^\d{9}$/ },
  { name: "Sao Tome and Principe", code: "+239", regex: /^\d{7}$/ },
  { name: "Saudi Arabia", code: "+966", regex: /^\d{9}$/ },
  { name: "Senegal", code: "+221", regex: /^\d{9}$/ },
  { name: "Serbia", code: "+381", regex: /^\d{9}$/ },
  { name: "Seychelles", code: "+248", regex: /^\d{7}$/ },
  { name: "Sierra Leone", code: "+232", regex: /^\d{8}$/ },
  { name: "Singapore", code: "+65", regex: /^\d{8}$/ },
  { name: "Slovakia", code: "+421", regex: /^\d{9}$/ },
  { name: "Slovenia", code: "+386", regex: /^\d{8}$/ },
  { name: "Solomon Islands", code: "+677", regex: /^\d{7}$/ },
  { name: "Somalia", code: "+252", regex: /^\d{8,9}$/ },
  { name: "South Africa", code: "+27", regex: /^\d{9}$/ },
  { name: "South Korea", code: "+82", regex: /^\d{9,10}$/ },
  { name: "Spain", code: "+34", regex: /^\d{9}$/ },
  { name: "Sri Lanka", code: "+94", regex: /^\d{9}$/ },
  { name: "Sudan", code: "+249", regex: /^\d{9}$/ },
  { name: "Suriname", code: "+597", regex: /^\d{7}$/ },
  { name: "Sweden", code: "+46", regex: /^\d{9}$/ },
  { name: "Switzerland", code: "+41", regex: /^\d{9}$/ },
  { name: "Syria", code: "+963", regex: /^\d{9}$/ },
  { name: "Taiwan", code: "+886", regex: /^\d{9}$/ },
  { name: "Tajikistan", code: "+992", regex: /^\d{9}$/ },
  { name: "Tanzania", code: "+255", regex: /^\d{9}$/ },
  { name: "Thailand", code: "+66", regex: /^\d{9}$/ },
  { name: "Timor-Leste", code: "+670", regex: /^\d{7}$/ },
  { name: "Togo", code: "+228", regex: /^\d{8}$/ },
  { name: "Tonga", code: "+676", regex: /^\d{5}$/ },
  { name: "Trinidad and Tobago", code: "+1-868", regex: /^\d{7}$/ },
  { name: "Tunisia", code: "+216", regex: /^\d{8}$/ },
  { name: "Turkey", code: "+90", regex: /^\d{10}$/ },
  { name: "Turkmenistan", code: "+993", regex: /^\d{8}$/ },
  { name: "Tuvalu", code: "+688", regex: /^\d{5}$/ },
  { name: "Uganda", code: "+256", regex: /^\d{9}$/ },
  { name: "Ukraine", code: "+380", regex: /^\d{9}$/ },
  { name: "United Arab Emirates", code: "+971", regex: /^\d{9}$/ },
  { name: "United Kingdom", code: "+44", regex: /^\d{10}$/ },
  { name: "United States", code: "+1", regex: /^\d{10}$/ },
  { name: "Uruguay", code: "+598", regex: /^\d{8}$/ },
  { name: "Uzbekistan", code: "+998", regex: /^\d{9}$/ },
  { name: "Vanuatu", code: "+678", regex: /^\d{7}$/ },
  { name: "Vatican City", code: "+379", regex: /^\d{8}$/ },
  { name: "Venezuela", code: "+58", regex: /^\d{10}$/ },
  { name: "Vietnam", code: "+84", regex: /^\d{9,10}$/ },
  { name: "Yemen", code: "+967", regex: /^\d{9}$/ },
  { name: "Zambia", code: "+260", regex: /^\d{9}$/ },
  { name: "Zimbabwe", code: "+263", regex: /^\d{9}$/ },
];
